version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cambi_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: cambi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: cambi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cambi.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
